import { MineData } from "./MineCard";

export const minesData: MineData[] = [
    {
        id: 1,
        pairName: "KEY–BUSD LP",
        pairIcons: ["/images/mining-card/1.png"],
        badge: "60X",
        noFees: true,
        apr: "38.06%",
        stack: "KEY–BUSD LP",
        earn: "KEY",
        depositFee: "0%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "KEY–BUSD LP",
        totalValue: "$47,976",
        earnValue: "$0",
    },
    {
        id: 2,
        pairName: "KEY–BNB LP",
        pairIcons: ["/images/mining-card/2.png"],
        badge: "60X",
        noFees: true,
        apr: "29.15%",
        stack: "KEY–BNB LP",
        earn: "KEY",
        depositFee: "0%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "KEY–BNB LP",
        totalValue: "$60,441",
        earnValue: "$0",
    },
    {
        id: 3,
        pairName: "TYPH-BUSD LP",
        pairIcons: ["/images/mining-card/3.png"],
        badge: "2X",
        noFees: true,
        apr: "28.98%",
        stack: "TYPH-BUSD LP",
        earn: "KEY",
        depositFee: "0%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "TYPH-BUSD LP",
        totalValue: "$2,588",
        earnValue: "$0",
    },
    {
        id: 4,
        pairName: "BNB-BUSD LP",
        pairIcons: ["/images/mining-card/4.png"],
        badge: "5X",
        apr: "3.28%",
        stack: "BNB-BUSD LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "BNB-BUSD LP",
        totalValue: "$17,963",
        earnValue: "$0",
    },
    {
        id: 5,
        pairName: "USDT-BUSD LP",
        pairIcons: ["/images/mining-card/5.png"],
        badge: "4X",
        apr: "9.83%",
        stack: "USDT-BUSD LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "USDT-BUSD LP",
        totalValue: "$1,919",
        earnValue: "$0",
    },
    {
        id: 6,
        pairName: "BTCB-BNB LP",
        pairIcons: ["/images/mining-card/6.png"],
        badge: "2X",
        apr: "10.26%",
        stack: "BTCB-BNB LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "BTCB-BNB LP",
        totalValue: "$1,001",
        earnValue: "$0",
    },
    {
        id: 7,
        pairName: "ETH-BNB LP",
        pairIcons: ["/images/mining-card/7.png"],
        badge: "4X",
        apr: "14.45%",
        stack: "ETH-BNB LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "ETH-BNB LP",
        totalValue: "$12,511",
        earnValue: "$0",
    },
    {
        id: 8,
        pairName: "DAI-BUSD LP",
        pairIcons: ["/images/mining-card/8.png"],
        badge: "4X",
        apr: "9.95%",
        stack: "DAI-BUSD LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "DAI-BUSD LP",
        totalValue: "$12,886",
        earnValue: "$0",
    },
    {
        id: 9,
        pairName: "USDC-BUSD LP",
        pairIcons: ["/images/mining-card/9.png"],
        badge: "6X",
        apr: "8.65%",
        stack: "USDC-BUSD LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "USDC-BUSD LP",
        totalValue: "$14,710",
        earnValue: "$0",
    },
    {
        id: 10,
        pairName: "DOT-BNB LP",
        pairIcons: ["/images/mining-card/10.png"],
        badge: "4X",
        apr: "22.30%",
        stack: "DOT-BNB LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "DOT-BNB LP",
        totalValue: "$9,480",
        earnValue: "$0",
    },
    {
        id: 11,
        pairName: "CAKE-BUSD LP",
        pairIcons: ["/images/mining-card/11.png"],
        badge: "2X",
        apr: "7.73%",
        stack: "CAKE-BUSD LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "CAKE-BUSD LP",
        totalValue: "$7,865",
        earnValue: "$0",
    },
    {
        id: 12,
        pairName: "CAKE-BNB LP",
        pairIcons: ["/images/mining-card/12.png"],
        badge: "2X",
        apr: "12.96%",
        stack: "CAKE-BNB LP",
        earn: "KEY",
        depositFee: "1.5%",
        keysEarned: 0,
        lpStacked: "KEY–BUSD LP STACKED",
        deposit: "CAKE-BNB LP",
        totalValue: "$4,586",
        earnValue: "$0",
    },
];
